const bcrypt = require('bcryptjs');
const { db, logAudit } = require('./db');

function seedDatabase() {
  console.log('--- Starting AIIA CTMS Database Seeding ---');

  // Clear existing data
  db.exec(`
    DELETE FROM adverse_events;
    DELETE FROM protocol_deviations;
    DELETE FROM trials;
    DELETE FROM audit_log;
    DELETE FROM password_resets;
    DELETE FROM users;
  `);

  const passwordHash = bcrypt.hashSync('password123', 10);

  // 1. Seed Users (All 7 Roles)
  const users = [
    {
      full_name: 'Dr. Anand Vaidya',
      email: 'pi.vaidya@aiia.gov.in',
      designation: 'Principal Investigator (PI)',
      department: 'Kayachikitsa',
      organization: 'All India Institute of Ayurveda, New Delhi'
    },
    {
      full_name: 'Dr. Meera Nambiar',
      email: 'pi.nambiar@aiia.gov.in',
      designation: 'Principal Investigator (PI)',
      department: 'Panchakarma',
      organization: 'All India Institute of Ayurveda, New Delhi'
    },
    {
      full_name: 'Pooja Sharma',
      email: 'coordinator.sharma@aiia.gov.in',
      designation: 'Study Coordinator',
      department: 'Clinical Research',
      organization: 'All India Institute of Ayurveda, New Delhi'
    },
    {
      full_name: 'Vikram Kapoor',
      email: 'monitor.kapoor@aiia.gov.in',
      designation: 'Clinical Monitor',
      department: 'Clinical Research',
      organization: 'National Pharmacovigilance Centre, New Delhi'
    },
    {
      full_name: 'Prof. Harish Chandra Verma',
      email: 'ethics.verma@aiia.gov.in',
      designation: 'Ethics Committee Member',
      department: 'Institutional Ethics Committee',
      organization: 'All India Institute of Ayurveda, New Delhi'
    },
    {
      full_name: 'Dr. Shalini Joshi',
      email: 'pv.joshi@aiia.gov.in',
      designation: 'Pharmacovigilance Officer',
      department: 'Pharmacovigilance',
      organization: 'Intermediary Pharmacovigilance Centre, AIIA'
    },
    {
      full_name: 'Administrator AIIA',
      email: 'admin@aiia.gov.in',
      designation: 'Institutional Admin',
      department: 'Clinical Research Directorate',
      organization: 'All India Institute of Ayurveda, New Delhi'
    },
    {
      full_name: 'Dr. Rajesh Bhushan (Ayush Regulatory Cell)',
      email: 'regulator.ayush@gov.in',
      designation: 'Regulator',
      department: 'Drug Controller General / Ministry of Ayush',
      organization: 'Ministry of Ayush, Govt of India'
    }
  ];

  const insertUser = db.prepare(`
    INSERT INTO users (full_name, email, password_hash, designation, department, organization)
    VALUES (?, ?, ?, ?, ?, ?)
  `);

  const userIds = {};
  users.forEach(u => {
    const res = insertUser.run(u.full_name, u.email, passwordHash, u.designation, u.department, u.organization);
    userIds[u.email] = res.lastInsertRowid;
  });

  console.log(`✓ Seeded ${users.length} user personas`);

  // 2. Seed 24 Realistic Ayurveda Clinical Trials
  const trials = [
    {
      ctri_number: 'CTRI/2025/01/078120',
      public_title: 'Evaluation of Ashwagandha Ghana Vati in Generalized Anxiety Disorder (Chittodvega)',
      scientific_title: 'A Double-Blind, Randomized, Placebo-Controlled Phase 3 Clinical Evaluation of Standardized Withania Somnifera Extract in Adult Chittodvega',
      pi_name: 'Dr. Anand Vaidya',
      pi_id: userIds['pi.vaidya@aiia.gov.in'],
      department: 'Kayachikitsa',
      site_name: 'AIIA Hospital Complex, Sarita Vihar, New Delhi',
      ethics_status: 'Approved',
      ethics_approval_date: '2025-01-10',
      ethics_notes: 'Full institutional ethical clearance granted with quarterly safety monitor review.',
      dcgi_approval: 'Yes',
      health_condition: 'Generalized Anxiety Disorder (Chittodvega)',
      study_type: 'Interventional',
      phase: 'Phase 3',
      intervention: 'Standardized Ashwagandha Root Extract (500mg twice daily with warm milk)',
      comparator: 'Matched Placebo Cellulose Capsule twice daily',
      target_sample_size_india: 240,
      target_sample_size_total: 240,
      current_enrollment: 188,
      recruitment_status: 'Open to recruitment',
      date_of_first_enrollment: '2025-02-01',
      estimated_duration: '18 Months',
      current_stage: 'Enrollment'
    },
    {
      ctri_number: 'CTRI/2024/08/071490',
      public_title: 'Efficacy of Matra Basti with Sahacharadi Taila in Lumbar Spondylosis (Kati Graha)',
      scientific_title: 'Comparative Randomized Controlled Trial Evaluating Sahacharadi Taila Matra Basti versus Oral NSAIDs in Chronic Lumbar Radiculopathy',
      pi_name: 'Dr. Meera Nambiar',
      pi_id: userIds['pi.nambiar@aiia.gov.in'],
      department: 'Panchakarma',
      site_name: 'AIIA Panchakarma IPD Ward & Research Wing',
      ethics_status: 'Approved',
      ethics_approval_date: '2024-08-15',
      ethics_notes: 'Approved with requirement of weekly ESR and sensory nerve conduction monitoring.',
      dcgi_approval: 'Yes',
      health_condition: 'Lumbar Spondylosis with Sciatica (Kati Graha & Gridhrasi)',
      study_type: 'Interventional',
      phase: 'Phase 2',
      intervention: 'Sahacharadi Taila Matra Basti (60ml trans-rectal daily for 16 consecutive days)',
      comparator: 'Standard Aceclofenac + Paracetamol 100mg/325mg tablet orally twice daily',
      target_sample_size_india: 120,
      target_sample_size_total: 120,
      current_enrollment: 120,
      recruitment_status: 'Completed',
      date_of_first_enrollment: '2024-09-01',
      estimated_duration: '12 Months',
      current_stage: 'Data Collection'
    },
    {
      ctri_number: 'CTRI/2025/03/082104',
      public_title: 'Safety and Efficacy of Guduchi-Tulsi-Yastimadhu Decoction in Post-Viral Fatigue Syndrome',
      scientific_title: 'Multicentric Adaptive Trial Assessing Immunomodulatory Ayush Kwatha Formulations in Chronic Post-Viral Asthenia',
      pi_name: 'Dr. Anand Vaidya',
      pi_id: userIds['pi.vaidya@aiia.gov.in'],
      department: 'Kayachikitsa',
      site_name: 'AIIA Hospital Clinical Research Unit',
      ethics_status: 'Approved',
      ethics_approval_date: '2025-02-28',
      ethics_notes: 'Approved under expedited post-viral clinical trial review guideline.',
      dcgi_approval: 'Yes',
      health_condition: 'Post-Viral Chronic Fatigue (Kshina Dhatu Janya Klama)',
      study_type: 'Interventional',
      phase: 'Phase 2',
      intervention: 'Hydro-ethanolic Kwatha (Tinospora cordifolia + Ocimum sanctum + Glycyrrhiza glabra) 40ml bd',
      comparator: 'Multivitamin & Zinc mineral supplementation once daily',
      target_sample_size_india: 160,
      target_sample_size_total: 160,
      current_enrollment: 94,
      recruitment_status: 'Open to recruitment',
      date_of_first_enrollment: '2025-03-15',
      estimated_duration: '14 Months',
      current_stage: 'Enrollment'
    },
    {
      ctri_number: 'CTRI/2024/11/076211',
      public_title: 'Curcumin and Boswellia Complex in Osteoarthritis of the Knee (Sandhigata Vata)',
      scientific_title: 'A Triple-Blind Active-Controlled Non-Inferiority Study of Bio-enhanced Curcuma longa and Boswellia serrata in Kellgren-Lawrence Grade II/III Knee OA',
      pi_name: 'Dr. Anand Vaidya',
      pi_id: userIds['pi.vaidya@aiia.gov.in'],
      department: 'Kayachikitsa',
      site_name: 'AIIA Clinical Trial Center, Outpatient Block C',
      ethics_status: 'Approved',
      ethics_approval_date: '2024-11-20',
      ethics_notes: 'Approved with strict monitoring of gastrointestinal tolerability.',
      dcgi_approval: 'Yes',
      health_condition: 'Knee Osteoarthritis (Janu Sandhigata Vata)',
      study_type: 'Interventional',
      phase: 'Phase 3',
      intervention: 'Standardized Curcuminoids + AKBA Boswellia capsule (500mg bd post meals)',
      comparator: 'Glucosamine Sulfate + Chondroitin 1500mg/1200mg orally daily',
      target_sample_size_india: 300,
      target_sample_size_total: 300,
      current_enrollment: 245,
      recruitment_status: 'Open to recruitment',
      date_of_first_enrollment: '2024-12-05',
      estimated_duration: '24 Months',
      current_stage: 'Enrollment'
    },
    {
      ctri_number: 'CTRI/2025/04/083901',
      public_title: 'Nasya Karma with Ksheerabala 101 in Migraine and Chronic Tension Headache (Shirashoola)',
      scientific_title: 'Pragmatic Randomized Trial of Pratimarsha Nasya using Ksheerabala Taila versus Flunarizine in Frequent Episodic Migraine',
      pi_name: 'Dr. Meera Nambiar',
      pi_id: userIds['pi.nambiar@aiia.gov.in'],
      department: 'Panchakarma',
      site_name: 'AIIA Shalakya & Panchakarma Department',
      ethics_status: 'Approved',
      ethics_approval_date: '2025-03-30',
      ethics_notes: 'Ethics approval cleared; periodic safety reports mandated.',
      dcgi_approval: 'Yes',
      health_condition: 'Migraine without Aura (Ardhavabhedaka)',
      study_type: 'Interventional',
      phase: 'Phase 2',
      intervention: 'Intranasal Pratimarsha Nasya 2 drops per nostril twice daily with lukewarm Ksheerabala 101',
      comparator: 'Flunarizine Hydrochloride 10mg orally at bedtime',
      target_sample_size_india: 100,
      target_sample_size_total: 100,
      current_enrollment: 42,
      recruitment_status: 'Open to recruitment',
      date_of_first_enrollment: '2025-04-10',
      estimated_duration: '12 Months',
      current_stage: 'Enrollment'
    },
    {
      ctri_number: 'CTRI/2024/05/068019',
      public_title: 'Brahmi Ghrita in Age-Associated Memory Impairment and Mild Cognitive Decline (Smriti Bhramsha)',
      scientific_title: 'Prospective Randomized Double-Blind Placebo-Controlled Study of Bacopa monnieri Medicated Ghee in Mild Cognitive Impairment',
      pi_name: 'Dr. Anand Vaidya',
      pi_id: userIds['pi.vaidya@aiia.gov.in'],
      department: 'Kayachikitsa',
      site_name: 'AIIA Geriatric Clinical Research OPD',
      ethics_status: 'Approved',
      ethics_approval_date: '2024-05-18',
      ethics_notes: 'Ethics committee cleared protocol with monthly MoCA score audits.',
      dcgi_approval: 'Yes',
      health_condition: 'Mild Cognitive Impairment (Smriti Hani)',
      study_type: 'Interventional',
      phase: 'Phase 2',
      intervention: 'Standardized Brahmi Ghrita 10g orally twice daily with lukewarm milk',
      comparator: 'Plain Cow Ghee (Go-Ghrita) 10g orally twice daily with lukewarm milk',
      target_sample_size_india: 150,
      target_sample_size_total: 150,
      current_enrollment: 150,
      recruitment_status: 'Completed',
      date_of_first_enrollment: '2024-06-01',
      estimated_duration: '18 Months',
      current_stage: 'Trial Closeout'
    },
    {
      ctri_number: 'CTRI/2025/02/080512',
      public_title: 'Shirodhara with Brahmi Taila in Primary Chronic Insomnia (Anidra)',
      scientific_title: 'Investigating Autonomic Tone and Sleep Architecture Modulation through Takradhara and Shirodhara in Treatment-Resistant Insomnia',
      pi_name: 'Dr. Meera Nambiar',
      pi_id: userIds['pi.nambiar@aiia.gov.in'],
      department: 'Panchakarma',
      site_name: 'AIIA Sleep Medicine and Panchakarma Unit',
      ethics_status: 'Approved',
      ethics_approval_date: '2025-01-25',
      ethics_notes: 'Approved with polysomnography monitoring protocol.',
      dcgi_approval: 'Yes',
      health_condition: 'Primary Chronic Insomnia (Anidra)',
      study_type: 'Interventional',
      phase: 'Phase 2',
      intervention: 'Shirodhara 45 mins daily for 14 days using medicated Brahmi Taila at 38°C',
      comparator: 'Cognitive Behavioral Therapy for Insomnia (CBT-I) bi-weekly sessions',
      target_sample_size_india: 80,
      target_sample_size_total: 80,
      current_enrollment: 58,
      recruitment_status: 'Open to recruitment',
      date_of_first_enrollment: '2025-02-15',
      estimated_duration: '10 Months',
      current_stage: 'Enrollment'
    },
    {
      ctri_number: 'CTRI/2025/05/085440',
      public_title: 'Saptamrit Lauha and Triphala Ghrita in Computer Vision Syndrome (Shushkakshipaka)',
      scientific_title: 'Open Label Interventional Trial on Ocular Surface Stability and Tear Breakup Time using Herbo-Mineral Ayurvedic Formulations in CVS',
      pi_name: 'Dr. Anand Vaidya',
      pi_id: userIds['pi.vaidya@aiia.gov.in'],
      department: 'Dravyaguna',
      site_name: 'AIIA Shalakya Tantra Dry Eye Specialty Clinic',
      ethics_status: 'Submitted',
      ethics_approval_date: null,
      ethics_notes: 'Protocol presented in IEC meeting; pending minor clarification on heavy metal testing report.',
      dcgi_approval: 'Yes',
      health_condition: 'Computer Vision Syndrome / Dry Eye Disease (Shushkakshipaka)',
      study_type: 'Interventional',
      phase: 'Phase 2',
      intervention: 'Saptamrit Lauha 250mg bd with Honey & Ghrita + Triphala Ghrita Tarpana',
      comparator: 'Carboxymethylcellulose 0.5% lubricant eye drops 4 times daily',
      target_sample_size_india: 100,
      target_sample_size_total: 100,
      current_enrollment: 0,
      recruitment_status: 'Not yet recruiting',
      date_of_first_enrollment: null,
      estimated_duration: '12 Months',
      current_stage: 'Ethics Approval'
    },
    {
      ctri_number: 'CTRI/2024/09/073180',
      public_title: 'Vamana Karma with Ikshvaku Bija Yoga in Chronic Plaque Psoriasis (Kitibha Kushtha)',
      scientific_title: 'Therapeutic Evaluation of Shodhana (Vamana) Followed by Somraji Taila in Psoriasis Area and Severity Index (PASI-75) Outcomes',
      pi_name: 'Dr. Meera Nambiar',
      pi_id: userIds['pi.nambiar@aiia.gov.in'],
      department: 'Panchakarma',
      site_name: 'AIIA Skin Research and Panchakarma Center',
      ethics_status: 'Approved',
      ethics_approval_date: '2024-09-12',
      ethics_notes: 'Approved with mandatory hydration and electrolyte panels before and after Vamana.',
      dcgi_approval: 'Yes',
      health_condition: 'Chronic Plaque Psoriasis (Kitibha Kushtha)',
      study_type: 'Interventional',
      phase: 'Phase 2',
      intervention: 'Classical Snehana-Swedana followed by Vamana with Ikshvaku Bija Yoga',
      comparator: 'Standard Topical Clobetasol Propionate 0.05% ointment bd',
      target_sample_size_india: 90,
      target_sample_size_total: 90,
      current_enrollment: 76,
      recruitment_status: 'Open to recruitment',
      date_of_first_enrollment: '2024-10-01',
      estimated_duration: '18 Months',
      current_stage: 'Enrollment'
    },
    {
      ctri_number: 'CTRI/2024/03/065120',
      public_title: 'Varunadi Kwatha and Gokshuradi Guggulu in Benign Prostatic Hyperplasia (Mutraghata)',
      scientific_title: 'Multicenter Non-Inferiority Trial of Varunadi Kwatha vs Tamsulosin in IPSS Score Reduction for Moderate BPH',
      pi_name: 'Dr. Anand Vaidya',
      pi_id: userIds['pi.vaidya@aiia.gov.in'],
      department: 'Kayachikitsa',
      site_name: 'AIIA Uro-Ayurveda Specialized OPD',
      ethics_status: 'Approved',
      ethics_approval_date: '2024-03-22',
      ethics_notes: 'Cleared. Uroflowmetry data verification mandatory at weeks 4, 8, 12.',
      dcgi_approval: 'Yes',
      health_condition: 'Benign Prostatic Hyperplasia (Vatasthila / Mutraghata)',
      study_type: 'Interventional',
      phase: 'Phase 3',
      intervention: 'Varunadi Kwatha 40ml bd + Gokshuradi Guggulu 2 tabs (500mg) tds post meals',
      comparator: 'Tamsulosin Hydrochloride 0.4mg sustained release capsule OD at night',
      target_sample_size_india: 220,
      target_sample_size_total: 220,
      current_enrollment: 220,
      recruitment_status: 'Completed',
      date_of_first_enrollment: '2024-04-15',
      estimated_duration: '16 Months',
      current_stage: 'Data Collection'
    },
    {
      ctri_number: 'CTRI/2025/06/087119',
      public_title: 'Ksharasutra Therapy versus Laser Hemorrhoidoplasty in Grade III Arsha (Hemorrhoids)',
      scientific_title: 'A Single-Blind Randomized Equivalence Trial of Apamarga Ksharasutra in Complicated Internal-External Hemorrhoids',
      pi_name: 'Dr. Meera Nambiar',
      pi_id: userIds['pi.nambiar@aiia.gov.in'],
      department: 'Clinical Research',
      site_name: 'AIIA Shalya Tantra Surgical Wing & Day Care Unit',
      ethics_status: 'Submitted',
      ethics_approval_date: null,
      ethics_notes: 'Protocol under IEC sub-committee clinical scrutiny.',
      dcgi_approval: 'Yes',
      health_condition: '3rd Degree Internal & External Hemorrhoids (Arsha)',
      study_type: 'Interventional',
      phase: 'Phase 3',
      intervention: 'Standard Apamarga Ksharasutra ligation under regional perianal anesthesia',
      comparator: 'Diode Laser Hemorrhoidoplasty (LHP) 1470nm fiber delivery',
      target_sample_size_india: 180,
      target_sample_size_total: 180,
      current_enrollment: 0,
      recruitment_status: 'Not yet recruiting',
      date_of_first_enrollment: null,
      estimated_duration: '20 Months',
      current_stage: 'Ethics Approval'
    },
    {
      ctri_number: 'CTRI/2024/07/070241',
      public_title: 'Nisha Amalaki and Mamajjaka Churna in Newly Diagnosed Type 2 Diabetes Mellitus (Madhumeha)',
      scientific_title: 'Glycemic Control and Beta-cell Preservative Potential of Curcuma longa, Emblica officinalis and Enicostemma littorale in Pre-diabetic and Early T2DM',
      pi_name: 'Dr. Anand Vaidya',
      pi_id: userIds['pi.vaidya@aiia.gov.in'],
      department: 'Kayachikitsa',
      site_name: 'AIIA Metabolic & Endocrine OPD Room 14',
      ethics_status: 'Approved',
      ethics_approval_date: '2024-07-02',
      ethics_notes: 'Approved with HbA1c testing scheduled at baseline, 3, 6, and 12 months.',
      dcgi_approval: 'Yes',
      health_condition: 'Type 2 Diabetes Mellitus (Madhumeha)',
      study_type: 'Interventional',
      phase: 'Phase 3',
      intervention: 'Standardized Nisha Amalaki powder 3g bd + Mamajjaka Ghanavati 500mg bd',
      comparator: 'Metformin Hydrochloride 500mg prolonged release tablet bd',
      target_sample_size_india: 260,
      target_sample_size_total: 260,
      current_enrollment: 210,
      recruitment_status: 'Open to recruitment',
      date_of_first_enrollment: '2024-07-20',
      estimated_duration: '24 Months',
      current_stage: 'Enrollment'
    },
    {
      ctri_number: 'CTRI/2025/01/079320',
      public_title: 'Arjuna Ksheerapaka in Mild Essential Hypertension (Rakta Gata Vata)',
      scientific_title: 'Ambulatory Blood Pressure Monitoring Assessment in Patients Administered Terminalia arjuna Bark Decoction Infused with Milk',
      pi_name: 'Dr. Anand Vaidya',
      pi_id: userIds['pi.vaidya@aiia.gov.in'],
      department: 'Kayachikitsa',
      site_name: 'AIIA Cardio-Ayurveda Research Unit',
      ethics_status: 'Approved',
      ethics_approval_date: '2025-01-14',
      ethics_notes: 'Cleared. 24-hour Holter and ABPM mandatory at week 0 and week 12.',
      dcgi_approval: 'Yes',
      health_condition: 'Essential Hypertension Stage-I (Rakta Capa)',
      study_type: 'Interventional',
      phase: 'Phase 2',
      intervention: 'Standardized Terminalia arjuna Ksheerapaka 50ml freshly prepared twice daily',
      comparator: 'Telmisartan 20mg tablet orally once daily',
      target_sample_size_india: 140,
      target_sample_size_total: 140,
      current_enrollment: 65,
      recruitment_status: 'Open to recruitment',
      date_of_first_enrollment: '2025-02-10',
      estimated_duration: '14 Months',
      current_stage: 'Enrollment'
    },
    {
      ctri_number: 'CTRI/2024/10/074819',
      public_title: 'Shigru Guggulu and Rasna Saptaka Kwatha in Rheumatoid Arthritis (Amavata)',
      scientific_title: 'Multi-Center Randomized Evaluation of Anti-inflammatory Markers (CRP, RF, anti-CCP) in Classical Ayurveda Protocol vs Hydroxychloroquine in Amavata',
      pi_name: 'Dr. Anand Vaidya',
      pi_id: userIds['pi.vaidya@aiia.gov.in'],
      department: 'Kayachikitsa',
      site_name: 'AIIA Autoimmune & Rheumatology OPD',
      ethics_status: 'Approved',
      ethics_approval_date: '2024-10-10',
      ethics_notes: 'Approved. DAS-28 scoring system implemented as primary outcome.',
      dcgi_approval: 'Yes',
      health_condition: 'Seropositive Rheumatoid Arthritis (Amavata)',
      study_type: 'Interventional',
      phase: 'Phase 3',
      intervention: 'Shigru Guggulu 1000mg bd + Rasna Saptaka Kwatha 40ml bd before food',
      comparator: 'Hydroxychloroquine 200mg orally once daily + Methotrexate 10mg weekly',
      target_sample_size_india: 200,
      target_sample_size_total: 200,
      current_enrollment: 135,
      recruitment_status: 'Open to recruitment',
      date_of_first_enrollment: '2024-11-01',
      estimated_duration: '24 Months',
      current_stage: 'Enrollment'
    },
    {
      ctri_number: 'CTRI/2025/03/081992',
      public_title: 'Pushyanuga Churna and Lodhrasava in Abnormal Uterine Bleeding (Asrigdara)',
      scientific_title: 'Randomized Comparative Study of Classical Hemostatic Herbal Formulations in Perimenopausal Dysfunctional Uterine Bleeding',
      pi_name: 'Dr. Meera Nambiar',
      pi_id: userIds['pi.nambiar@aiia.gov.in'],
      department: 'Clinical Research',
      site_name: 'AIIA Prasuti Tantra & Stri Roga Wing',
      ethics_status: 'Approved',
      ethics_approval_date: '2025-02-18',
      ethics_notes: 'Approved. Endometrial biopsy mandatory pre-enrollment.',
      dcgi_approval: 'Yes',
      health_condition: 'Abnormal Uterine Bleeding (Asrigdara / Pradara)',
      study_type: 'Interventional',
      phase: 'Phase 2',
      intervention: 'Pushyanuga Churna 3g bd with Tandulodaka + Lodhrasava 20ml bd with equal water',
      comparator: 'Tranexamic Acid 500mg tablet thrice daily during active bleeding days',
      target_sample_size_india: 120,
      target_sample_size_total: 120,
      current_enrollment: 51,
      recruitment_status: 'Open to recruitment',
      date_of_first_enrollment: '2025-03-01',
      estimated_duration: '12 Months',
      current_stage: 'Enrollment'
    },
    {
      ctri_number: 'CTRI/2023/12/061298',
      public_title: 'Bhumyamalaki and Katuki in Non-Alcoholic Fatty Liver Disease (Yakrit Roga)',
      scientific_title: 'FibroScan and Liver Enzymes Guided Evaluation of Phyllanthus niruri and Picrorhiza kurroa in Metabolic Associated Steatohepatitis',
      pi_name: 'Dr. Anand Vaidya',
      pi_id: userIds['pi.vaidya@aiia.gov.in'],
      department: 'Kayachikitsa',
      site_name: 'AIIA Hepatobiliary Research OPD',
      ethics_status: 'Approved',
      ethics_approval_date: '2023-12-15',
      ethics_notes: 'Approved with ultrasound elastography validation protocol.',
      dcgi_approval: 'Yes',
      health_condition: 'Non-Alcoholic Fatty Liver Disease / Steatohepatitis (Yakritodara)',
      study_type: 'Interventional',
      phase: 'Phase 3',
      intervention: 'Bhumyamalaki tablet 500mg bd + Arogyavardhini Vati 250mg bd',
      comparator: 'Saroglitazar 4mg orally once daily',
      target_sample_size_india: 180,
      target_sample_size_total: 180,
      current_enrollment: 180,
      recruitment_status: 'Completed',
      date_of_first_enrollment: '2024-01-10',
      estimated_duration: '20 Months',
      current_stage: 'Trial Closeout'
    },
    {
      ctri_number: 'CTRI/2025/05/086111',
      public_title: 'Agastya Haritaki Avaleha in Chronic Bronchial Asthma (Tamaka Shwasa)',
      scientific_title: 'Spirometric FEV1/FVC and Quality of Life Outcome Study of Agastya Haritaki in Adult Persistent Allergic Bronchial Asthma',
      pi_name: 'Dr. Anand Vaidya',
      pi_id: userIds['pi.vaidya@aiia.gov.in'],
      department: 'Kayachikitsa',
      site_name: 'AIIA Pulmonary Care Center',
      ethics_status: 'Approved',
      ethics_approval_date: '2025-05-02',
      ethics_notes: 'Approved. Emergency Salbutamol inhaler rescue protocol documented.',
      dcgi_approval: 'Yes',
      health_condition: 'Persistent Bronchial Asthma (Tamaka Shwasa)',
      study_type: 'Interventional',
      phase: 'Phase 2',
      intervention: 'Agastya Haritaki Avaleha 10g twice daily with lukewarm water',
      comparator: 'Budesonide/Formoterol 200/6mcg DPI inhaler twice daily',
      target_sample_size_india: 110,
      target_sample_size_total: 110,
      current_enrollment: 18,
      recruitment_status: 'Open to recruitment',
      date_of_first_enrollment: '2025-05-15',
      estimated_duration: '14 Months',
      current_stage: 'Enrollment'
    },
    {
      ctri_number: 'CTRI/2024/02/063810',
      public_title: 'Kanchanara Guggulu and Jalaukavacharana in Chronic Non-Healing Venous Ulcers (Dushta Vrana)',
      scientific_title: 'Leech Therapy (Hirudotherapy) Combined with Herbo-mineral Formulations in Chronic Venous Leg Stasis Ulcers: A Controlled Cohort',
      pi_name: 'Dr. Meera Nambiar',
      pi_id: userIds['pi.nambiar@aiia.gov.in'],
      department: 'Panchakarma',
      site_name: 'AIIA Wound Management Clinic & Shalya IPD',
      ethics_status: 'Approved',
      ethics_approval_date: '2024-02-12',
      ethics_notes: 'Cleared with strict bacteriological culture testing of Hirudo medicinalis tanks.',
      dcgi_approval: 'Yes',
      health_condition: 'Chronic Venous Leg Ulcer (Dushta Vrana)',
      study_type: 'Interventional',
      phase: 'Phase 2',
      intervention: 'Weekly Jalaukavacharana (4-6 live leeches per ulcer) + Jatyadi Taila sterile dressing',
      comparator: 'Modern hydrocolloid compression bandage changed twice weekly',
      target_sample_size_india: 80,
      target_sample_size_total: 80,
      current_enrollment: 80,
      recruitment_status: 'Completed',
      date_of_first_enrollment: '2024-03-01',
      estimated_duration: '12 Months',
      current_stage: 'Trial Closeout'
    },
    {
      ctri_number: 'CTRI/2025/04/084502',
      public_title: 'Shankhapushpi Syrup in Attention Deficit Hyperactivity Disorder (ADHD) in Children',
      scientific_title: 'A Pediatric Double-Blind Placebo-Controlled Trial of Convolvulus pluricaulis in ADHD Vanderbilt Assessment Scale Improvement',
      pi_name: 'Dr. Anand Vaidya',
      pi_id: userIds['pi.vaidya@aiia.gov.in'],
      department: 'Kayachikitsa',
      site_name: 'AIIA Kaumarbhritya (Pediatrics) Child Guidance Clinic',
      ethics_status: 'Approved',
      ethics_approval_date: '2025-03-12',
      ethics_notes: 'Pediatric ethics subcommittee approval cleared with parental assent process.',
      dcgi_approval: 'Yes',
      health_condition: 'Pediatric ADHD (Unmada / Medha Mandya)',
      study_type: 'Interventional',
      phase: 'Phase 2',
      intervention: 'Standardized Shankhapushpi Syrup 10ml twice daily with water',
      comparator: 'Flavored placebo syrup matching color and viscosity 10ml twice daily',
      target_sample_size_india: 90,
      target_sample_size_total: 90,
      current_enrollment: 28,
      recruitment_status: 'Open to recruitment',
      date_of_first_enrollment: '2025-04-01',
      estimated_duration: '16 Months',
      current_stage: 'Enrollment'
    },
    {
      ctri_number: 'CTRI/2025/06/088001',
      public_title: 'Triphala Mandoor and Punarnavadi Kwatha in Chronic Iron Deficiency Anemia (Pandu Roga)',
      scientific_title: 'Comparative Bioavailability and Hemoglobin Elevation Trial of Ferric Herbo-Mineral Complex vs Ferrous Ascorbate',
      pi_name: 'Dr. Anand Vaidya',
      pi_id: userIds['pi.vaidya@aiia.gov.in'],
      department: 'Dravyaguna',
      site_name: 'AIIA Clinical Pathology & Hematology Research Lab',
      ethics_status: 'Approved',
      ethics_approval_date: '2025-05-20',
      ethics_notes: 'Approved. Ferritin and TIBC indices tracked every 30 days.',
      dcgi_approval: 'Yes',
      health_condition: 'Iron Deficiency Anemia (Pandu Roga)',
      study_type: 'Interventional',
      phase: 'Phase 3',
      intervention: 'Triphala Mandoor 500mg bd with Takra (Buttermilk) + Punarnavadi Kwatha 30ml bd',
      comparator: 'Ferrous Ascorbate 100mg + Folic Acid 1.5mg tablet once daily',
      target_sample_size_india: 160,
      target_sample_size_total: 160,
      current_enrollment: 12,
      recruitment_status: 'Open to recruitment',
      date_of_first_enrollment: '2025-06-05',
      estimated_duration: '10 Months',
      current_stage: 'Site Activation'
    },
    {
      ctri_number: 'CTRI/2024/06/069500',
      public_title: 'Jatamansi and Tagara in Generalized Sleep-Wake Rhythm Disturbance in Shift Workers',
      scientific_title: 'Circadian Phase Shift and Melatonin Rhythm Evaluation in Night Shift Healthcare Workers using Nardostachys jatamansi Formulation',
      pi_name: 'Dr. Meera Nambiar',
      pi_id: userIds['pi.nambiar@aiia.gov.in'],
      department: 'Panchakarma',
      site_name: 'AIIA Occupational Health Clinic',
      ethics_status: 'Approved',
      ethics_approval_date: '2024-06-18',
      ethics_notes: 'Approved. Actigraphy watch sleep log protocol approved.',
      dcgi_approval: 'Yes',
      health_condition: 'Shift Work Sleep Disorder (Kala Viparyaya Anidra)',
      study_type: 'Interventional',
      phase: 'Phase 2',
      intervention: 'Jatamansi extract 500mg + Tagara extract 250mg capsule 30 mins before target sleep',
      comparator: 'Melatonin 3mg orally 30 mins before target sleep',
      target_sample_size_india: 100,
      target_sample_size_total: 100,
      current_enrollment: 88,
      recruitment_status: 'Open to recruitment',
      date_of_first_enrollment: '2024-07-05',
      estimated_duration: '15 Months',
      current_stage: 'Enrollment'
    },
    {
      ctri_number: 'CTRI/2025/07/089400',
      public_title: 'Siddha Makardhwaja in Post-Chemotherapy Peripheral Neuropathy (Vata Prakopa)',
      scientific_title: 'Phase 1 Safety, Tolerability and Pharmacokinetics Study of Purified Siddha Makardhwaja in Solid Tumor Neuropathy',
      pi_name: 'Dr. Anand Vaidya',
      pi_id: userIds['pi.vaidya@aiia.gov.in'],
      department: 'Clinical Research',
      site_name: 'AIIA Integrative Oncology Research Unit',
      ethics_status: 'Not submitted',
      ethics_approval_date: null,
      ethics_notes: 'Draft protocol under pre-submission scientific committee review.',
      dcgi_approval: 'No',
      health_condition: 'Chemotherapy-Induced Peripheral Neuropathy (Suptata / Harsha)',
      study_type: 'Interventional',
      phase: 'Phase 1',
      intervention: 'Siddha Makardhwaja 65mg with Betel Leaf juice and Honey once daily',
      comparator: 'None (Dose-escalation single arm Phase 1)',
      target_sample_size_india: 30,
      target_sample_size_total: 30,
      current_enrollment: 0,
      recruitment_status: 'Not yet recruiting',
      date_of_first_enrollment: null,
      estimated_duration: '18 Months',
      current_stage: 'Ethics Approval'
    },
    {
      ctri_number: 'CTRI/2024/04/067115',
      public_title: 'Takradhara in Chronic Plaque Psoriasis and Scalp Seborrhea',
      scientific_title: 'Assessment of Scalp Barrier Function and Systemic Inflammatory Cytokines with Takradhara Protocol in Scalp Psoriasis',
      pi_name: 'Dr. Meera Nambiar',
      pi_id: userIds['pi.nambiar@aiia.gov.in'],
      department: 'Panchakarma',
      site_name: 'AIIA Panchakarma Center OPD 7',
      ethics_status: 'Approved',
      ethics_approval_date: '2024-04-10',
      ethics_notes: 'Ethics approved with DLQI (Dermatology Life Quality Index) questionnaire.',
      dcgi_approval: 'Yes',
      health_condition: 'Scalp Psoriasis (Darunaka & Kitibha)',
      study_type: 'Interventional',
      phase: 'Phase 2',
      intervention: 'Takradhara (Mustadi processed medicated buttermilk) 45 mins daily for 10 days',
      comparator: 'Coal Tar 1% + Salicylic Acid 3% therapeutic shampoo applied thrice weekly',
      target_sample_size_india: 70,
      target_sample_size_total: 70,
      current_enrollment: 70,
      recruitment_status: 'Completed',
      date_of_first_enrollment: '2024-05-01',
      estimated_duration: '12 Months',
      current_stage: 'Data Collection'
    },
    {
      ctri_number: 'CTRI/2025/05/086701',
      public_title: 'Yastimadhu and Shankhapushpi in Perimenopausal Vasomotor Symptoms (Hot Flashes)',
      scientific_title: 'Kupperman Menopausal Index Evaluation in Perimenopausal Hot Flashes using Phytoestrogenic Ayurvedic Formulations',
      pi_name: 'Dr. Anand Vaidya',
      pi_id: userIds['pi.vaidya@aiia.gov.in'],
      department: 'Dravyaguna',
      site_name: 'AIIA Womens Wellness Research Clinic',
      ethics_status: 'Approved',
      ethics_approval_date: '2025-04-20',
      ethics_notes: 'Approved. Transvaginal sonography safety monitoring scheduled at 6 months.',
      dcgi_approval: 'Yes',
      health_condition: 'Menopausal Hot Flashes & Night Sweats (Rajonivritti Janya Lakshana)',
      study_type: 'Interventional',
      phase: 'Phase 3',
      intervention: 'Standardized Glycyrrhiza glabra tablet 500mg bd + Shankhapushpi Ghanavati 500mg bd',
      comparator: 'Isoflavone Soy Phytoestrogen 60mg tablet once daily',
      target_sample_size_india: 150,
      target_sample_size_total: 150,
      current_enrollment: 60,
      recruitment_status: 'Open to recruitment',
      date_of_first_enrollment: '2025-05-10',
      estimated_duration: '15 Months',
      current_stage: 'Enrollment'
    }
  ];

  const insertTrial = db.prepare(`
    INSERT INTO trials (
      ctri_number, public_title, scientific_title, pi_name, pi_id, department, site_name,
      ethics_status, ethics_approval_date, ethics_notes, dcgi_approval, health_condition,
      study_type, phase, intervention, comparator, target_sample_size_india, target_sample_size_total,
      current_enrollment, recruitment_status, date_of_first_enrollment, estimated_duration,
      current_stage, created_by
    ) VALUES (
      ?, ?, ?, ?, ?, ?, ?,
      ?, ?, ?, ?, ?,
      ?, ?, ?, ?, ?, ?,
      ?, ?, ?, ?,
      ?, ?
    )
  `);

  const trialIds = [];
  trials.forEach(t => {
    const res = insertTrial.run(
      t.ctri_number, t.public_title, t.scientific_title, t.pi_name, t.pi_id, t.department, t.site_name,
      t.ethics_status, t.ethics_approval_date, t.ethics_notes, t.dcgi_approval, t.health_condition,
      t.study_type, t.phase, t.intervention, t.comparator, t.target_sample_size_india, t.target_sample_size_total,
      t.current_enrollment, t.recruitment_status, t.date_of_first_enrollment, t.estimated_duration,
      t.current_stage, userIds['admin@aiia.gov.in']
    );
    trialIds.push({ id: res.lastInsertRowid, ctri: t.ctri_number });
  });

  console.log(`✓ Seeded ${trials.length} clinical trials with CTRI schemas`);

  // 3. Seed 35 Realistic Adverse Events (AE) and Serious Adverse Events (SAE)
  const meddraCodes = [
    { code: '10018043', term: 'Gastrointestinal - Hyperacidity (Amlapitta)' },
    { code: '10028813', term: 'Nausea and Emesis (Chhardi)' },
    { code: '10019211', term: 'Cephalea / Headache (Shiroruk)' },
    { code: '10037087', term: 'Cutaneous Pruritus / Itching (Kandu)' },
    { code: '10012735', term: 'Loose Stools / Diarrhea (Atisara)' },
    { code: '10041285', term: 'Somnolence / Excessive Drowsiness (Nidradhikya)' },
    { code: '10013649', term: 'Dizziness / Vertigo (Bhrama)' },
    { code: '10020084', term: 'Elevated Transaminases / Hepatotoxicity (Kamala)' },
    { code: '10001367', term: 'Abdominal Cramps / Colic (Udarashoola)' },
    { code: '10002198', term: 'Allergic Dermatitis / Rash (Kotha)' },
    { code: '10033557', term: 'Palpitations / Tachycardia (Hrid-drava)' },
    { code: '10016558', term: 'Fatigue and Asthenia (Klama / Daurbalya)' },
    { code: '10002855', term: 'Anaphylactoid Reaction (Teevrahita)' },
    { code: '10038359', term: 'Acute Renal Impairment (Mutrakrichhra)' },
    { code: '10022118', term: 'Hypoglycemic Episode (Kshudhadhikya)' },
    { code: '10013946', term: 'Dryness of Mouth (Mukhashosha)' },
    { code: '10019059', term: 'Joint Stiffness / Arthralgia (Sandhigraha)' },
    { code: '10021428', term: 'Insomnia exacerbation (Anidra)' }
  ];

  const adverseEvents = [
    // SAEs (Severe / Urgent reporting)
    {
      patient_id: 'P-1004',
      trial_idx: 0,
      event_description: 'Subject developed severe macular rash across thorax and face with localized angioedema 48 hours post initial dose of Ashwagandha extract.',
      severity: 'Severe',
      seriousness: 'SAE',
      event_date: '2026-09-24',
      report_date: '2026-09-25',
      meddra: meddraCodes[9],
      outcome: 'Recovering',
      causality: 'Probable',
      reporting_status: 'On-Time',
      action_taken: 'Investigational drug suspended immediately; treated with oral Cetirizine and low-dose Prednisolone in AIIA Day Care.'
    },
    {
      patient_id: 'P-1019',
      trial_idx: 3,
      event_description: 'Patient hospitalized with acute upper abdominal pain, grade 3 transaminitis (ALT 280 U/L, AST 210 U/L) on day 28 of Curcumin-Boswellia therapy.',
      severity: 'Severe',
      seriousness: 'SAE',
      event_date: '2026-09-18',
      report_date: '2026-09-20',
      meddra: meddraCodes[7],
      outcome: 'Recovering',
      causality: 'Possible',
      reporting_status: 'Overdue',
      action_taken: 'Study drug permanently withdrawn; liver ultrasound performed; patient monitored under gastroenterology consult.'
    },
    {
      patient_id: 'P-1082',
      trial_idx: 11,
      event_description: 'Sudden symptomatic hypoglycemia with diaphoresis, blood glucose dropped to 48 mg/dL during co-administration with metformin.',
      severity: 'Severe',
      seriousness: 'SAE',
      event_date: '2026-09-26',
      report_date: '2026-09-27',
      meddra: meddraCodes[14],
      outcome: 'Recovered',
      causality: 'Probable',
      reporting_status: 'On-Time',
      action_taken: 'Intravenous 25% Dextrose given; dosage of trial intervention titrated down by 50%.'
    },
    {
      patient_id: 'P-1120',
      trial_idx: 1,
      event_description: 'Severe rectal mucosal irritation and acute retention of urine following 5th session of Sahacharadi Matra Basti.',
      severity: 'Severe',
      seriousness: 'SAE',
      event_date: '2026-09-22',
      report_date: '2026-09-26',
      meddra: meddraCodes[13],
      outcome: 'Recovering',
      causality: 'Probable',
      reporting_status: 'Overdue',
      action_taken: 'Matra Basti discontinued; urinary catheterization done for 24h; proctoscopy showed mild proctitis.'
    },
    {
      patient_id: 'P-1045',
      trial_idx: 8,
      event_description: 'Severe dehydration with transient hypotension (BP 84/50 mmHg) and electrolyte imbalance following therapeutic Vamana induction.',
      severity: 'Severe',
      seriousness: 'SAE',
      event_date: '2026-09-25',
      report_date: '2026-09-26',
      meddra: meddraCodes[1],
      outcome: 'Recovered',
      causality: 'Certain',
      reporting_status: 'On-Time',
      action_taken: 'Patient admitted to ICU high-dependency unit, given 2.5L IV Ringer Lactate and oral ORS; discharged stable after 36h.'
    },

    // AEs (Moderate / Mild)
    {
      patient_id: 'P-1011',
      trial_idx: 0,
      event_description: 'Transient morning drowsiness and grogginess resolving within 2 hours of waking.',
      severity: 'Mild',
      seriousness: 'AE',
      event_date: '2026-09-12',
      report_date: '2026-09-13',
      meddra: meddraCodes[5],
      outcome: 'Recovered',
      causality: 'Probable',
      reporting_status: 'On-Time',
      action_taken: 'Patient advised to take dose 1 hour earlier before bedtime; no dose reduction required.'
    },
    {
      patient_id: 'P-1015',
      trial_idx: 0,
      event_description: 'Mild retrosternal burning and gastric fullness after swallowing capsule with empty stomach.',
      severity: 'Mild',
      seriousness: 'AE',
      event_date: '2026-09-14',
      report_date: '2026-09-15',
      meddra: meddraCodes[0],
      outcome: 'Recovered',
      causality: 'Probable',
      reporting_status: 'On-Time',
      action_taken: 'Advised strict intake with warm milk post meals.'
    },
    {
      patient_id: 'P-1022',
      trial_idx: 0,
      event_description: 'Moderate frontal headache reported during 2nd week of intervention.',
      severity: 'Moderate',
      seriousness: 'AE',
      event_date: '2026-09-08',
      report_date: '2026-09-10',
      meddra: meddraCodes[2],
      outcome: 'Recovered',
      causality: 'Unlikely',
      reporting_status: 'On-Time',
      action_taken: 'Single dose of Paracetamol 500mg given. Headache resolved.'
    },
    {
      patient_id: 'P-1033',
      trial_idx: 2,
      event_description: 'Bitter taste sensation lingering in oral cavity with mild nausea in early morning.',
      severity: 'Mild',
      seriousness: 'AE',
      event_date: '2026-09-16',
      report_date: '2026-09-17',
      meddra: meddraCodes[1],
      outcome: 'Recovering',
      causality: 'Certain',
      reporting_status: 'On-Time',
      action_taken: 'Patient advised to consume 1 teaspoon of honey post decoction ingestion.'
    },
    {
      patient_id: 'P-1048',
      trial_idx: 2,
      event_description: 'Moderate abdominal colic and increased bowel frequency (3 times/day).',
      severity: 'Moderate',
      seriousness: 'AE',
      event_date: '2026-09-19',
      report_date: '2026-09-20',
      meddra: meddraCodes[4],
      outcome: 'Recovered',
      causality: 'Probable',
      reporting_status: 'On-Time',
      action_taken: 'Dose decreased from 40ml to 25ml for 3 days; symptoms abated.'
    },
    {
      patient_id: 'P-1051',
      trial_idx: 3,
      event_description: 'Mild epigastric discomfort after evening tablet administration.',
      severity: 'Mild',
      seriousness: 'AE',
      event_date: '2026-09-05',
      report_date: '2026-09-06',
      meddra: meddraCodes[0],
      outcome: 'Recovered',
      causality: 'Possible',
      reporting_status: 'On-Time',
      action_taken: 'Taken with breakfast and dinner; symptoms subsided.'
    },
    {
      patient_id: 'P-1064',
      trial_idx: 3,
      event_description: 'Mild generalized pruritus without erythema.',
      severity: 'Mild',
      seriousness: 'AE',
      event_date: '2026-09-11',
      report_date: '2026-09-12',
      meddra: meddraCodes[3],
      outcome: 'Recovered',
      causality: 'Possible',
      reporting_status: 'On-Time',
      action_taken: 'Moisturizing lotion prescribed; study drug continued.'
    },
    {
      patient_id: 'P-1077',
      trial_idx: 4,
      event_description: 'Nasal burning sensation and sneezing paroxysms for 10 minutes following Pratimarsha Nasya.',
      severity: 'Mild',
      seriousness: 'AE',
      event_date: '2026-09-20',
      report_date: '2026-09-21',
      meddra: meddraCodes[3],
      outcome: 'Recovered',
      causality: 'Certain',
      reporting_status: 'On-Time',
      action_taken: 'Oil temperature checked and maintained at exactly 37°C before instillation.'
    },
    {
      patient_id: 'P-1089',
      trial_idx: 5,
      event_description: 'Mild loose motions during the first 3 days of Brahmi Ghrita intake.',
      severity: 'Mild',
      seriousness: 'AE',
      event_date: '2026-08-20',
      report_date: '2026-08-22',
      meddra: meddraCodes[4],
      outcome: 'Recovered',
      causality: 'Probable',
      reporting_status: 'On-Time',
      action_taken: 'Self-limiting physiological bowel adjustment to lipid formulation.'
    },
    {
      patient_id: 'P-1095',
      trial_idx: 6,
      event_description: 'Sensation of heaviness in the head post Shirodhara procedure.',
      severity: 'Mild',
      seriousness: 'AE',
      event_date: '2026-09-10',
      report_date: '2026-09-11',
      meddra: meddraCodes[2],
      outcome: 'Recovered',
      causality: 'Probable',
      reporting_status: 'On-Time',
      action_taken: 'Head washed with warm water; dry herbal hair drying advised.'
    },
    {
      patient_id: 'P-1102',
      trial_idx: 8,
      event_description: 'Mild erythematous flare around psoriatic plaque border on extremities.',
      severity: 'Moderate',
      seriousness: 'AE',
      event_date: '2026-09-15',
      report_date: '2026-09-16',
      meddra: meddraCodes[9],
      outcome: 'Recovering',
      causality: 'Possible',
      reporting_status: 'On-Time',
      action_taken: 'Topical coconut oil applied; dermatologist review scheduled.'
    },
    {
      patient_id: 'P-1115',
      trial_idx: 9,
      event_description: 'Frequent micturition episodes during daytime (diuretic effect).',
      severity: 'Mild',
      seriousness: 'AE',
      event_date: '2026-08-25',
      report_date: '2026-08-26',
      meddra: meddraCodes[13],
      outcome: 'Recovered',
      causality: 'Certain',
      reporting_status: 'On-Time',
      action_taken: 'Dose timing adjusted: evening dose shifted to 5 PM.'
    },
    {
      patient_id: 'P-1132',
      trial_idx: 11,
      event_description: 'Mild metallic taste and occasional belching.',
      severity: 'Mild',
      seriousness: 'AE',
      event_date: '2026-09-02',
      report_date: '2026-09-04',
      meddra: meddraCodes[0],
      outcome: 'Recovered',
      causality: 'Possible',
      reporting_status: 'On-Time',
      action_taken: 'Maintained hydration; no interruption of therapy.'
    },
    {
      patient_id: 'P-1140',
      trial_idx: 12,
      event_description: 'Transient postural lightheadedness when rising rapidly from supine position.',
      severity: 'Mild',
      seriousness: 'AE',
      event_date: '2026-09-14',
      report_date: '2026-09-15',
      meddra: meddraCodes[6],
      outcome: 'Recovered',
      causality: 'Probable',
      reporting_status: 'On-Time',
      action_taken: 'Counseling on gradual change of posture provided.'
    },
    {
      patient_id: 'P-1155',
      trial_idx: 13,
      event_description: 'Mild burning sensation in stomach with warm sensations in palms.',
      severity: 'Mild',
      seriousness: 'AE',
      event_date: '2026-09-01',
      report_date: '2026-09-03',
      meddra: meddraCodes[0],
      outcome: 'Recovered',
      causality: 'Probable',
      reporting_status: 'On-Time',
      action_taken: 'Administered with cold water or milk.'
    },
    {
      patient_id: 'P-1168',
      trial_idx: 14,
      event_description: 'Mild constipation and dry stool consistency.',
      severity: 'Mild',
      seriousness: 'AE',
      event_date: '2026-09-18',
      report_date: '2026-09-20',
      meddra: meddraCodes[4],
      outcome: 'Recovered',
      causality: 'Probable',
      reporting_status: 'On-Time',
      action_taken: 'Prescribed Isabgol husk 1 tablespoon at bedtime.'
    },
    {
      patient_id: 'P-1175',
      trial_idx: 15,
      event_description: 'Bitter belching and transient loose motions on Day 2 of Arogyavardhini.',
      severity: 'Moderate',
      seriousness: 'AE',
      event_date: '2026-08-10',
      report_date: '2026-08-12',
      meddra: meddraCodes[4],
      outcome: 'Recovered',
      causality: 'Certain',
      reporting_status: 'On-Time',
      action_taken: 'Therapeutic Katuki purgative effect; resolved without medical intervention.'
    },
    {
      patient_id: 'P-1188',
      trial_idx: 16,
      event_description: 'Mild throat tickle immediately following ingestion of Avaleha paste.',
      severity: 'Mild',
      seriousness: 'AE',
      event_date: '2026-09-21',
      report_date: '2026-09-22',
      meddra: meddraCodes[15],
      outcome: 'Recovered',
      causality: 'Probable',
      reporting_status: 'On-Time',
      action_taken: 'Sipped lukewarm water after ingestion.'
    },
    {
      patient_id: 'P-1194',
      trial_idx: 17,
      event_description: 'Local perilesional bleeding continued for 2 hours post leech detachment.',
      severity: 'Moderate',
      seriousness: 'AE',
      event_date: '2026-08-15',
      report_date: '2026-08-16',
      meddra: meddraCodes[10],
      outcome: 'Recovered',
      causality: 'Certain',
      reporting_status: 'On-Time',
      action_taken: 'Haridra (turmeric) pressure dressing applied; bleeding arrested promptly.'
    },
    {
      patient_id: 'P-1205',
      trial_idx: 18,
      event_description: 'Mild behavioral agitation and refusal to swallow syrup due to sweet-herbal taste.',
      severity: 'Mild',
      seriousness: 'AE',
      event_date: '2026-09-10',
      report_date: '2026-09-12',
      meddra: meddraCodes[11],
      outcome: 'Recovered',
      causality: 'Unlikely',
      reporting_status: 'On-Time',
      action_taken: 'Syrup mixed with fresh apple juice.'
    },
    {
      patient_id: 'P-1218',
      trial_idx: 20,
      event_description: 'Subject reported vivid dreaming and delayed wake time for 2 days.',
      severity: 'Mild',
      seriousness: 'AE',
      event_date: '2026-09-08',
      report_date: '2026-09-10',
      meddra: meddraCodes[5],
      outcome: 'Recovered',
      causality: 'Probable',
      reporting_status: 'On-Time',
      action_taken: 'Jatamansi dose reduced by 50%.'
    },
    {
      patient_id: 'P-1224',
      trial_idx: 22,
      event_description: 'Mild chills and shivering sensation during buttermilk scalp pour on rainy morning.',
      severity: 'Mild',
      seriousness: 'AE',
      event_date: '2026-08-28',
      report_date: '2026-08-29',
      meddra: meddraCodes[11],
      outcome: 'Recovered',
      causality: 'Probable',
      reporting_status: 'On-Time',
      action_taken: 'Room temperature maintained with infrared heater; Takra slightly warmed.'
    },
    {
      patient_id: 'P-1235',
      trial_idx: 23,
      event_description: 'Mild fluid retention / ankle swelling in late evening.',
      severity: 'Mild',
      seriousness: 'AE',
      event_date: '2026-09-15',
      report_date: '2026-09-17',
      meddra: meddraCodes[16],
      outcome: 'Recovering',
      causality: 'Possible',
      reporting_status: 'On-Time',
      action_taken: 'Dietary sodium restriction advised; blood pressure remains normal.'
    },
    {
      patient_id: 'P-1240',
      trial_idx: 0,
      event_description: 'Overdue adverse reaction report: Mild skin erythema observed on forearm on day 10.',
      severity: 'Mild',
      seriousness: 'AE',
      event_date: '2026-09-01',
      report_date: '2026-09-18',
      meddra: meddraCodes[9],
      outcome: 'Recovered',
      causality: 'Possible',
      reporting_status: 'Overdue',
      action_taken: 'Delayed reporting due to participant holiday travel; event resolved without therapy.'
    },
    {
      patient_id: 'P-1255',
      trial_idx: 3,
      event_description: 'Overdue AE: Transient episode of loose stools following festive food intake.',
      severity: 'Mild',
      seriousness: 'AE',
      event_date: '2026-09-03',
      report_date: '2026-09-22',
      meddra: meddraCodes[4],
      outcome: 'Recovered',
      causality: 'Unrelated',
      reporting_status: 'Overdue',
      action_taken: 'Determined to be dietary indiscretion; study medication was unaffected.'
    }
  ];

  const insertAE = db.prepare(`
    INSERT INTO adverse_events (
      patient_id, trial_id, event_description, severity, seriousness,
      event_date, report_date, meddra_code, meddra_term, outcome,
      causality, reporting_status, reported_by, action_taken
    ) VALUES (
      ?, ?, ?, ?, ?,
      ?, ?, ?, ?, ?,
      ?, ?, ?, ?
    )
  `);

  adverseEvents.forEach(ae => {
    const trial = trialIds[ae.trial_idx] || trialIds[0];
    insertAE.run(
      ae.patient_id,
      trial.id,
      ae.event_description,
      ae.severity,
      ae.seriousness,
      ae.event_date,
      ae.report_date,
      ae.meddra.code,
      ae.meddra.term,
      ae.outcome,
      ae.causality,
      ae.reporting_status,
      userIds['coordinator.sharma@aiia.gov.in'],
      ae.action_taken
    );
  });

  console.log(`✓ Seeded ${adverseEvents.length} adverse event reports (AE/SAE) with MedDRA mapping`);

  // 4. Seed Protocol Deviations (Flagged by Clinical Monitors)
  const protocolDeviations = [
    {
      trial_idx: 0,
      patient_id: 'P-1008',
      deviation_type: 'Visit out of window',
      description: 'Day 30 scheduled visit conducted at Day 41 due to subject transport disruption.',
      severity: 'Minor',
      action_taken: 'Coordinator instructed to contact subject 3 days in advance; calendar alert set.',
      status: 'Resolved',
      flagged_date: '2026-09-10'
    },
    {
      trial_idx: 0,
      patient_id: 'P-1014',
      deviation_type: 'Lab test missed',
      description: 'Serum cortisol baseline lab sample omitted by phlebotomist prior to drug administration.',
      severity: 'Major',
      action_taken: 'Sample recollected next morning after fasting confirmation; deviation noted in trial master file.',
      status: 'Under Review',
      flagged_date: '2026-09-18'
    },
    {
      trial_idx: 1,
      patient_id: 'P-1025',
      deviation_type: 'Dosing non-compliance',
      description: 'Subject missed 2 consecutive days of Sahacharadi Matra Basti over the weekend.',
      severity: 'Minor',
      action_taken: 'Subject retrained; two extra retention sessions appended to protocol schedule.',
      status: 'Resolved',
      flagged_date: '2026-09-14'
    },
    {
      trial_idx: 3,
      patient_id: 'P-1060',
      deviation_type: 'Prohibited concomitant medication',
      description: 'Subject took self-prescribed Ibuprofen 400mg for toothache while on active blinded therapy.',
      severity: 'Major',
      action_taken: 'Subject counseled on allowed rescue analgesics (Paracetamol only); wash-out recorded.',
      status: 'Open',
      flagged_date: '2026-09-22'
    },
    {
      trial_idx: 8,
      patient_id: 'P-1105',
      deviation_type: 'Inclusion/Exclusion criteria violation',
      description: 'Subject enrolled with baseline systolic BP of 162 mmHg (protocol ceiling is 160 mmHg).',
      severity: 'Critical',
      action_taken: 'Case referred to Principal Investigator; confirmed benign white-coat effect; repeat ABPM was 138/86.',
      status: 'Resolved',
      flagged_date: '2026-09-05'
    }
  ];

  const insertPD = db.prepare(`
    INSERT INTO protocol_deviations (
      trial_id, patient_id, deviation_type, description, severity,
      action_taken, status, flagged_by, flagged_date
    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
  `);

  protocolDeviations.forEach(pd => {
    const trial = trialIds[pd.trial_idx] || trialIds[0];
    insertPD.run(
      trial.id,
      pd.patient_id,
      pd.deviation_type,
      pd.description,
      pd.severity,
      pd.action_taken,
      pd.status,
      userIds['monitor.kapoor@aiia.gov.in'],
      pd.flagged_date
    );
  });

  console.log(`✓ Seeded ${protocolDeviations.length} protocol deviations`);

  // 5. Seed Audit Trail Logs
  const auditLogs = [
    {
      userId: userIds['admin@aiia.gov.in'],
      userName: 'Administrator AIIA',
      userRole: 'Institutional Admin',
      actionType: 'SYSTEM',
      entityAffected: 'SYSTEM',
      entityId: 'SYS-INIT',
      details: 'AIIA CTMS Platform v2.4 initialization and database schema verification.',
      ipAddress: '192.168.1.10'
    },
    {
      userId: userIds['pi.vaidya@aiia.gov.in'],
      userName: 'Dr. Anand Vaidya',
      userRole: 'Principal Investigator (PI)',
      actionType: 'CREATE',
      entityAffected: 'TRIAL',
      entityId: 'CTRI/2025/01/078120',
      details: 'Created new trial application: Ashwagandha Ghana Vati in Generalized Anxiety Disorder.',
      ipAddress: '192.168.1.45'
    },
    {
      userId: userIds['ethics.verma@aiia.gov.in'],
      userName: 'Prof. Harish Chandra Verma',
      userRole: 'Ethics Committee Member',
      actionType: 'APPROVE',
      entityAffected: 'ETHICS',
      entityId: 'CTRI/2025/01/078120',
      details: 'Approved Institutional Ethics clearance with quarterly safety audit condition.',
      ipAddress: '192.168.1.88'
    },
    {
      userId: userIds['coordinator.sharma@aiia.gov.in'],
      userName: 'Pooja Sharma',
      userRole: 'Study Coordinator',
      actionType: 'CREATE',
      entityAffected: 'ADVERSE_EVENT',
      entityId: 'P-1004',
      details: 'Submitted Serious Adverse Event (SAE) report: Macular rash and angioedema.',
      ipAddress: '192.168.1.52'
    },
    {
      userId: userIds['monitor.kapoor@aiia.gov.in'],
      userName: 'Vikram Kapoor',
      userRole: 'Clinical Monitor',
      actionType: 'FLAG',
      entityAffected: 'PROTOCOL_DEVIATION',
      entityId: 'P-1014',
      details: 'Flagged Major Protocol Deviation: Missed baseline serum cortisol collection.',
      ipAddress: '192.168.1.66'
    },
    {
      userId: userIds['pv.joshi@aiia.gov.in'],
      userName: 'Dr. Shalini Joshi',
      userRole: 'Pharmacovigilance Officer',
      actionType: 'UPDATE',
      entityAffected: 'ADVERSE_EVENT',
      entityId: 'P-1019',
      details: 'Updated causality assessment to Possible and flagged overdue regulatory notification.',
      ipAddress: '192.168.1.92'
    }
  ];

  auditLogs.forEach(a => logAudit(a));
  console.log(`✓ Seeded initial audit log entries`);

  console.log('--- AIIA CTMS Seeding Completed Successfully ---');
}

if (require.main === module) {
  seedDatabase();
}

module.exports = { seedDatabase };
